- project:
    templates:
      - publish-openstack-docs-pti
    check:
      jobs:
        - openstack-tox-pep8
        - openstack-tox-py38
        - openstack-tox-py39
        - openstack-tox-py310
        - openstack-tox-py311
    gate:
      jobs:
        - openstack-tox-pep8
        - openstack-tox-py38
        - openstack-tox-py39
        - openstack-tox-py310
        - openstack-tox-py311
